// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

namespace Pulumi.Contrib.Kubernetes.CertManager.Certmanager.V1.Inputs
{

    /// <summary>
    /// CertificateAdditionalOutputFormat defines an additional output format of a Certificate resource. These contain supplementary data formats of the signed certificate chain and paired private key.
    /// </summary>
    public class CertificateSpecAdditionalOutputFormatsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Type is the name of the format type that should be written to the Certificate's target Secret.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public CertificateSpecAdditionalOutputFormatsArgs()
        {
        }
        public static new CertificateSpecAdditionalOutputFormatsArgs Empty => new CertificateSpecAdditionalOutputFormatsArgs();
    }
}
