// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

namespace Pulumi.Contrib.Kubernetes.CertManager.Certmanager.V1.Inputs
{

    /// <summary>
    /// managed identity configuration, can not be used at the same time as clientID, clientSecretSecretRef or tenantID
    /// </summary>
    public class IssuerSpecAcmeSolversDns01AzureDNSManagedIdentityArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// client ID of the managed identity, can not be used at the same time as resourceID
        /// </summary>
        [Input("clientID")]
        public Input<string>? ClientID { get; set; }

        /// <summary>
        /// resource ID of the managed identity, can not be used at the same time as clientID
        /// </summary>
        [Input("resourceID")]
        public Input<string>? ResourceID { get; set; }

        public IssuerSpecAcmeSolversDns01AzureDNSManagedIdentityArgs()
        {
        }
        public static new IssuerSpecAcmeSolversDns01AzureDNSManagedIdentityArgs Empty => new IssuerSpecAcmeSolversDns01AzureDNSManagedIdentityArgs();
    }
}
