// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

namespace Pulumi.Contrib.Kubernetes.CertManager.Acme.V1.Inputs
{

    /// <summary>
    /// LocalObjectReference contains enough information to let you locate the referenced object inside the same namespace.
    /// </summary>
    public class ChallengeSpecSolverHttp01IngressPodTemplateSpecImagePullSecretsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public ChallengeSpecSolverHttp01IngressPodTemplateSpecImagePullSecretsArgs()
        {
        }
        public static new ChallengeSpecSolverHttp01IngressPodTemplateSpecImagePullSecretsArgs Empty => new ChallengeSpecSolverHttp01IngressPodTemplateSpecImagePullSecretsArgs();
    }
}
