// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1
{

    public class ApplicationSetSpecGeneratorsPluginInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("parameters")]
        private InputMap<ImmutableDictionary<string, object>>? _parameters;
        public InputMap<ImmutableDictionary<string, object>> Parameters
        {
            get => _parameters ?? (_parameters = new InputMap<ImmutableDictionary<string, object>>());
            set => _parameters = value;
        }

        public ApplicationSetSpecGeneratorsPluginInputArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorsPluginInputArgs Empty => new ApplicationSetSpecGeneratorsPluginInputArgs();
    }
}
