// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1
{

    public class ApplicationSetSpecGeneratorsMergeGeneratorsPullRequestFiltersArgs : global::Pulumi.ResourceArgs
    {
        [Input("branchMatch")]
        public Input<string>? BranchMatch { get; set; }

        [Input("targetBranchMatch")]
        public Input<string>? TargetBranchMatch { get; set; }

        public ApplicationSetSpecGeneratorsMergeGeneratorsPullRequestFiltersArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorsMergeGeneratorsPullRequestFiltersArgs Empty => new ApplicationSetSpecGeneratorsMergeGeneratorsPullRequestFiltersArgs();
    }
}
