// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1
{

    public class ApplicationSetSpecGeneratorsMatrixArgs : global::Pulumi.ResourceArgs
    {
        [Input("generators", required: true)]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMatrixGeneratorsArgs>? _generators;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMatrixGeneratorsArgs> Generators
        {
            get => _generators ?? (_generators = new InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMatrixGeneratorsArgs>());
            set => _generators = value;
        }

        [Input("template")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMatrixTemplateArgs>? Template { get; set; }

        public ApplicationSetSpecGeneratorsMatrixArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorsMatrixArgs Empty => new ApplicationSetSpecGeneratorsMatrixArgs();
    }
}
