// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1
{

    /// <summary>
    /// ApplicationStatus contains status information for the application
    /// </summary>
    public class ApplicationStatusArgs : global::Pulumi.ResourceArgs
    {
        [Input("conditions")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationStatusConditionsArgs>? _conditions;

        /// <summary>
        /// Conditions is a list of currently observed application conditions
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationStatusConditionsArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationStatusConditionsArgs>());
            set => _conditions = value;
        }

        /// <summary>
        /// ControllerNamespace indicates the namespace in which the application controller is located
        /// </summary>
        [Input("controllerNamespace")]
        public Input<string>? ControllerNamespace { get; set; }

        /// <summary>
        /// Health contains information about the application's current health status
        /// </summary>
        [Input("health")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationStatusHealthArgs>? Health { get; set; }

        [Input("history")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationStatusHistoryArgs>? _history;

        /// <summary>
        /// History contains information about the application's sync history
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationStatusHistoryArgs> History
        {
            get => _history ?? (_history = new InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationStatusHistoryArgs>());
            set => _history = value;
        }

        /// <summary>
        /// ObservedAt indicates when the application state was updated without querying latest git state Deprecated: controller no longer updates ObservedAt field
        /// </summary>
        [Input("observedAt")]
        public Input<string>? ObservedAt { get; set; }

        /// <summary>
        /// OperationState contains information about any ongoing operations, such as a sync
        /// </summary>
        [Input("operationState")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationStatusOperationStateArgs>? OperationState { get; set; }

        /// <summary>
        /// ReconciledAt indicates when the application state was reconciled using the latest git version
        /// </summary>
        [Input("reconciledAt")]
        public Input<string>? ReconciledAt { get; set; }

        /// <summary>
        /// ResourceHealthSource indicates where the resource health status is stored: inline if not set or appTree
        /// </summary>
        [Input("resourceHealthSource")]
        public Input<string>? ResourceHealthSource { get; set; }

        [Input("resources")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationStatusResourcesArgs>? _resources;

        /// <summary>
        /// Resources is a list of Kubernetes resources managed by this application
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationStatusResourcesArgs> Resources
        {
            get => _resources ?? (_resources = new InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationStatusResourcesArgs>());
            set => _resources = value;
        }

        /// <summary>
        /// SourceType specifies the type of this application
        /// </summary>
        [Input("sourceType")]
        public Input<string>? SourceType { get; set; }

        [Input("sourceTypes")]
        private InputList<string>? _sourceTypes;

        /// <summary>
        /// SourceTypes specifies the type of the sources included in the application
        /// </summary>
        public InputList<string> SourceTypes
        {
            get => _sourceTypes ?? (_sourceTypes = new InputList<string>());
            set => _sourceTypes = value;
        }

        /// <summary>
        /// Summary contains a list of URLs and container images used by this application
        /// </summary>
        [Input("summary")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationStatusSummaryArgs>? Summary { get; set; }

        /// <summary>
        /// Sync contains information about the application's current sync status
        /// </summary>
        [Input("sync")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationStatusSyncArgs>? Sync { get; set; }

        public ApplicationStatusArgs()
        {
        }
        public static new ApplicationStatusArgs Empty => new ApplicationStatusArgs();
    }
}
