// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1
{

    /// <summary>
    /// Automated will keep an application synced to the target revision
    /// </summary>
    public class ApplicationSpecSyncPolicyAutomatedArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// AllowEmpty allows apps have zero live resources (default: false)
        /// </summary>
        [Input("allowEmpty")]
        public Input<bool>? AllowEmpty { get; set; }

        /// <summary>
        /// Prune specifies whether to delete resources from the cluster that are not found in the sources anymore as part of automated sync (default: false)
        /// </summary>
        [Input("prune")]
        public Input<bool>? Prune { get; set; }

        /// <summary>
        /// SelfHeal specifies whether to revert resources back to their desired state upon modification in the cluster (default: false)
        /// </summary>
        [Input("selfHeal")]
        public Input<bool>? SelfHeal { get; set; }

        public ApplicationSpecSyncPolicyAutomatedArgs()
        {
        }
        public static new ApplicationSpecSyncPolicyAutomatedArgs Empty => new ApplicationSpecSyncPolicyAutomatedArgs();
    }
}
