// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1
{

    /// <summary>
    /// OrphanedResourceKey is a reference to a resource to be ignored from
    /// </summary>
    public class AppProjectSpecOrphanedResourcesIgnoreArgs : global::Pulumi.ResourceArgs
    {
        [Input("group")]
        public Input<string>? Group { get; set; }

        [Input("kind")]
        public Input<string>? Kind { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public AppProjectSpecOrphanedResourcesIgnoreArgs()
        {
        }
        public static new AppProjectSpecOrphanedResourcesIgnoreArgs Empty => new AppProjectSpecOrphanedResourcesIgnoreArgs();
    }
}
