// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

namespace Pulumi.Contrib.Kubernetes.CertManager.Certmanager.V1.Outputs
{

    /// <summary>
    /// ACME specific status options. This field should only be set if the Issuer is configured to use an ACME server to issue certificates.
    /// </summary>
    [OutputType]
    public sealed class ClusterIssuerStatusAcme
    {
        /// <summary>
        /// LastPrivateKeyHash is a hash of the private key associated with the latest registered ACME account, in order to track changes made to registered account associated with the Issuer
        /// </summary>
        public readonly string LastPrivateKeyHash;
        /// <summary>
        /// LastRegisteredEmail is the email associated with the latest registered ACME account, in order to track changes made to registered account associated with the  Issuer
        /// </summary>
        public readonly string LastRegisteredEmail;
        /// <summary>
        /// URI is the unique account identifier, which can also be used to retrieve account details from the CA
        /// </summary>
        public readonly string Uri;

        [OutputConstructor]
        private ClusterIssuerStatusAcme(
            string lastPrivateKeyHash,

            string lastRegisteredEmail,

            string uri)
        {
            LastPrivateKeyHash = lastPrivateKeyHash;
            LastRegisteredEmail = lastRegisteredEmail;
            Uri = uri;
        }
    }
}
