// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;

namespace Pulumi.Contrib.Kubernetes.CertManager.Certmanager.V1.Outputs
{

    /// <summary>
    /// Status of the Issuer. This is set and managed automatically.
    /// </summary>
    [OutputType]
    public sealed class IssuerStatus
    {
        /// <summary>
        /// ACME specific status options. This field should only be set if the Issuer is configured to use an ACME server to issue certificates.
        /// </summary>
        public readonly IssuerStatusAcme Acme;
        /// <summary>
        /// List of status conditions to indicate the status of a CertificateRequest. Known condition types are `Ready`.
        /// </summary>
        public readonly ImmutableArray<IssuerStatusConditions> Conditions;

        [OutputConstructor]
        private IssuerStatus(
            IssuerStatusAcme acme,

            ImmutableArray<IssuerStatusConditions> conditions)
        {
            Acme = acme;
            Conditions = conditions;
        }
    }
}
