// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

namespace Pulumi.Contrib.Kubernetes.CertManager.Certmanager.V1.Outputs
{

    /// <summary>
    /// managed identity configuration, can not be used at the same time as clientID, clientSecretSecretRef or tenantID
    /// </summary>
    [OutputType]
    public sealed class IssuerSpecAcmeSolversDns01AzureDNSManagedIdentity
    {
        /// <summary>
        /// client ID of the managed identity, can not be used at the same time as resourceID
        /// </summary>
        public readonly string ClientID;
        /// <summary>
        /// resource ID of the managed identity, can not be used at the same time as clientID
        /// </summary>
        public readonly string ResourceID;

        [OutputConstructor]
        private IssuerSpecAcmeSolversDns01AzureDNSManagedIdentity(
            string clientID,

            string resourceID)
        {
            ClientID = clientID;
            ResourceID = resourceID;
        }
    }
}
