// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1
{

    /// <summary>
    /// ResourceResult holds the operation result details of a specific resource
    /// </summary>
    [OutputType]
    public sealed class ApplicationStatusOperationStateSyncResultResources
    {
        /// <summary>
        /// Group specifies the API group of the resource
        /// </summary>
        public readonly string Group;
        /// <summary>
        /// HookPhase contains the state of any operation associated with this resource OR hook This can also contain values for non-hook resources.
        /// </summary>
        public readonly string HookPhase;
        /// <summary>
        /// HookType specifies the type of the hook. Empty for non-hook resources
        /// </summary>
        public readonly string HookType;
        /// <summary>
        /// Kind specifies the API kind of the resource
        /// </summary>
        public readonly string Kind;
        /// <summary>
        /// Message contains an informational or error message for the last sync OR operation
        /// </summary>
        public readonly string Message;
        /// <summary>
        /// Name specifies the name of the resource
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Namespace specifies the target namespace of the resource
        /// </summary>
        public readonly string Namespace;
        /// <summary>
        /// Status holds the final result of the sync. Will be empty if the resources is yet to be applied/pruned and is always zero-value for hooks
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// SyncPhase indicates the particular phase of the sync that this result was acquired in
        /// </summary>
        public readonly string SyncPhase;
        /// <summary>
        /// Version specifies the API version of the resource
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private ApplicationStatusOperationStateSyncResultResources(
            string group,

            string hookPhase,

            string hookType,

            string kind,

            string message,

            string name,

            string @namespace,

            string status,

            string syncPhase,

            string version)
        {
            Group = group;
            HookPhase = hookPhase;
            HookType = hookType;
            Kind = kind;
            Message = message;
            Name = name;
            Namespace = @namespace;
            Status = status;
            SyncPhase = syncPhase;
            Version = version;
        }
    }
}
