// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1
{

    [OutputType]
    public sealed class ApplicationSetStatusApplicationStatus
    {
        public readonly string Application;
        public readonly string LastTransitionTime;
        public readonly string Message;
        public readonly string Status;
        public readonly string Step;

        [OutputConstructor]
        private ApplicationSetStatusApplicationStatus(
            string application,

            string lastTransitionTime,

            string message,

            string status,

            string step)
        {
            Application = application;
            LastTransitionTime = lastTransitionTime;
            Message = message;
            Status = status;
            Step = step;
        }
    }
}
