// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorsMatrixGeneratorsGit
    {
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMatrixGeneratorsGitDirectories> Directories;
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMatrixGeneratorsGitFiles> Files;
        public readonly string PathParamPrefix;
        public readonly string RepoURL;
        public readonly int RequeueAfterSeconds;
        public readonly string Revision;
        public readonly Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMatrixGeneratorsGitTemplate Template;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorsMatrixGeneratorsGit(
            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMatrixGeneratorsGitDirectories> directories,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMatrixGeneratorsGitFiles> files,

            string pathParamPrefix,

            string repoURL,

            int requeueAfterSeconds,

            string revision,

            Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMatrixGeneratorsGitTemplate template)
        {
            Directories = directories;
            Files = files;
            PathParamPrefix = pathParamPrefix;
            RepoURL = repoURL;
            RequeueAfterSeconds = requeueAfterSeconds;
            Revision = revision;
            Template = template;
        }
    }
}
