// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1
{

    /// <summary>
    /// HelmFileParameter is a file parameter that's passed to helm template during manifest generation
    /// </summary>
    [OutputType]
    public sealed class ApplicationStatusOperationStateSyncResultSourceHelmFileParameters
    {
        /// <summary>
        /// Name is the name of the Helm parameter
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Path is the path to the file containing the values for the Helm parameter
        /// </summary>
        public readonly string Path;

        [OutputConstructor]
        private ApplicationStatusOperationStateSyncResultSourceHelmFileParameters(
            string name,

            string path)
        {
            Name = name;
            Path = path;
        }
    }
}
