// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1
{

    /// <summary>
    /// RevisionHistory contains history information about a previous sync
    /// </summary>
    [OutputType]
    public sealed class ApplicationStatusHistory
    {
        /// <summary>
        /// DeployStartedAt holds the time the sync operation started
        /// </summary>
        public readonly string DeployStartedAt;
        /// <summary>
        /// DeployedAt holds the time the sync operation completed
        /// </summary>
        public readonly string DeployedAt;
        /// <summary>
        /// ID is an auto incrementing identifier of the RevisionHistory
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// Revision holds the revision the sync was performed against
        /// </summary>
        public readonly string Revision;
        /// <summary>
        /// Revisions holds the revision of each source in sources field the sync was performed against
        /// </summary>
        public readonly ImmutableArray<string> Revisions;
        /// <summary>
        /// Source is a reference to the application source used for the sync operation
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationStatusHistorySource Source;
        /// <summary>
        /// Sources is a reference to the application sources used for the sync operation
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationStatusHistorySources> Sources;

        [OutputConstructor]
        private ApplicationStatusHistory(
            string deployStartedAt,

            string deployedAt,

            int id,

            string revision,

            ImmutableArray<string> revisions,

            Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationStatusHistorySource source,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationStatusHistorySources> sources)
        {
            DeployStartedAt = deployStartedAt;
            DeployedAt = deployedAt;
            Id = id;
            Revision = revision;
            Revisions = revisions;
            Source = source;
            Sources = sources;
        }
    }
}
