// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorsMergeGeneratorsScmProviderAzureDevOps
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMergeGeneratorsScmProviderAzureDevOpsAccessTokenRef AccessTokenRef;
        public readonly bool AllBranches;
        public readonly string Api;
        public readonly string Organization;
        public readonly string TeamProject;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorsMergeGeneratorsScmProviderAzureDevOps(
            Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMergeGeneratorsScmProviderAzureDevOpsAccessTokenRef accessTokenRef,

            bool allBranches,

            string api,

            string organization,

            string teamProject)
        {
            AccessTokenRef = accessTokenRef;
            AllBranches = allBranches;
            Api = api;
            Organization = organization;
            TeamProject = teamProject;
        }
    }
}
