// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorsMergeGeneratorsGitTemplateSpecIgnoreDifferences
    {
        public readonly string Group;
        public readonly ImmutableArray<string> JqPathExpressions;
        public readonly ImmutableArray<string> JsonPointers;
        public readonly string Kind;
        public readonly ImmutableArray<string> ManagedFieldsManagers;
        public readonly string Name;
        public readonly string Namespace;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorsMergeGeneratorsGitTemplateSpecIgnoreDifferences(
            string group,

            ImmutableArray<string> jqPathExpressions,

            ImmutableArray<string> jsonPointers,

            string kind,

            ImmutableArray<string> managedFieldsManagers,

            string name,

            string @namespace)
        {
            Group = group;
            JqPathExpressions = jqPathExpressions;
            JsonPointers = jsonPointers;
            Kind = kind;
            ManagedFieldsManagers = managedFieldsManagers;
            Name = name;
            Namespace = @namespace;
        }
    }
}
