// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1
{

    [OutputType]
    public sealed class ApplicationSetSpecTemplateSpecSourcesPluginParameters
    {
        public readonly ImmutableArray<string> Array;
        public readonly ImmutableDictionary<string, string> Map;
        public readonly string Name;
        public readonly string String;

        [OutputConstructor]
        private ApplicationSetSpecTemplateSpecSourcesPluginParameters(
            ImmutableArray<string> array,

            ImmutableDictionary<string, string> map,

            string name,

            string @string)
        {
            Array = array;
            Map = map;
            Name = name;
            String = @string;
        }
    }
}
