// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorsMergeGeneratorsClusterDecisionResource
    {
        public readonly string ConfigMapRef;
        public readonly Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMergeGeneratorsClusterDecisionResourceLabelSelector LabelSelector;
        public readonly string Name;
        public readonly int RequeueAfterSeconds;
        public readonly Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMergeGeneratorsClusterDecisionResourceTemplate Template;
        public readonly ImmutableDictionary<string, string> Values;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorsMergeGeneratorsClusterDecisionResource(
            string configMapRef,

            Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMergeGeneratorsClusterDecisionResourceLabelSelector labelSelector,

            string name,

            int requeueAfterSeconds,

            Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMergeGeneratorsClusterDecisionResourceTemplate template,

            ImmutableDictionary<string, string> values)
        {
            ConfigMapRef = configMapRef;
            LabelSelector = labelSelector;
            Name = name;
            RequeueAfterSeconds = requeueAfterSeconds;
            Template = template;
            Values = values;
        }
    }
}
