// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1
{

    /// <summary>
    /// ResourceStatus holds the current sync and health status of a resource TODO: describe members of this type
    /// </summary>
    [OutputType]
    public sealed class ApplicationStatusResources
    {
        public readonly string Group;
        /// <summary>
        /// HealthStatus contains information about the currently observed health state of an application or resource
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationStatusResourcesHealth Health;
        public readonly bool Hook;
        public readonly string Kind;
        public readonly string Name;
        public readonly string Namespace;
        public readonly bool RequiresPruning;
        /// <summary>
        /// SyncStatusCode is a type which represents possible comparison results
        /// </summary>
        public readonly string Status;
        public readonly int SyncWave;
        public readonly string Version;

        [OutputConstructor]
        private ApplicationStatusResources(
            string group,

            Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationStatusResourcesHealth health,

            bool hook,

            string kind,

            string name,

            string @namespace,

            bool requiresPruning,

            string status,

            int syncWave,

            string version)
        {
            Group = group;
            Health = health;
            Hook = hook;
            Kind = kind;
            Name = name;
            Namespace = @namespace;
            RequiresPruning = requiresPruning;
            Status = status;
            SyncWave = syncWave;
            Version = version;
        }
    }
}
