// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1
{

    /// <summary>
    /// Jsonnet holds options specific to Jsonnet
    /// </summary>
    [OutputType]
    public sealed class ApplicationStatusHistorySourcesDirectoryJsonnet
    {
        /// <summary>
        /// ExtVars is a list of Jsonnet External Variables
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationStatusHistorySourcesDirectoryJsonnetExtVars> ExtVars;
        /// <summary>
        /// Additional library search dirs
        /// </summary>
        public readonly ImmutableArray<string> Libs;
        /// <summary>
        /// TLAS is a list of Jsonnet Top-level Arguments
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationStatusHistorySourcesDirectoryJsonnetTlas> Tlas;

        [OutputConstructor]
        private ApplicationStatusHistorySourcesDirectoryJsonnet(
            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationStatusHistorySourcesDirectoryJsonnetExtVars> extVars,

            ImmutableArray<string> libs,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationStatusHistorySourcesDirectoryJsonnetTlas> tlas)
        {
            ExtVars = extVars;
            Libs = libs;
            Tlas = tlas;
        }
    }
}
