// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorsClustersTemplateSpec
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsClustersTemplateSpecDestination Destination;
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsClustersTemplateSpecIgnoreDifferences> IgnoreDifferences;
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsClustersTemplateSpecInfo> Info;
        public readonly string Project;
        public readonly int RevisionHistoryLimit;
        public readonly Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsClustersTemplateSpecSource Source;
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsClustersTemplateSpecSources> Sources;
        public readonly Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsClustersTemplateSpecSyncPolicy SyncPolicy;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorsClustersTemplateSpec(
            Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsClustersTemplateSpecDestination destination,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsClustersTemplateSpecIgnoreDifferences> ignoreDifferences,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsClustersTemplateSpecInfo> info,

            string project,

            int revisionHistoryLimit,

            Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsClustersTemplateSpecSource source,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsClustersTemplateSpecSources> sources,

            Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsClustersTemplateSpecSyncPolicy syncPolicy)
        {
            Destination = destination;
            IgnoreDifferences = ignoreDifferences;
            Info = info;
            Project = project;
            RevisionHistoryLimit = revisionHistoryLimit;
            Source = source;
            Sources = sources;
            SyncPolicy = syncPolicy;
        }
    }
}
