// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1
{

    /// <summary>
    /// Retry controls the strategy to apply if a sync fails
    /// </summary>
    [OutputType]
    public sealed class ApplicationStatusOperationStateOperationRetry
    {
        /// <summary>
        /// Backoff controls how to backoff on subsequent retries of failed syncs
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationStatusOperationStateOperationRetryBackoff Backoff;
        /// <summary>
        /// Limit is the maximum number of attempts for retrying a failed sync. If set to 0, no retries will be performed.
        /// </summary>
        public readonly int Limit;

        [OutputConstructor]
        private ApplicationStatusOperationStateOperationRetry(
            Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationStatusOperationStateOperationRetryBackoff backoff,

            int limit)
        {
            Backoff = backoff;
            Limit = limit;
        }
    }
}
