// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorsMatrixGeneratorsPlugin
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMatrixGeneratorsPluginConfigMapRef ConfigMapRef;
        public readonly Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMatrixGeneratorsPluginInput Input;
        public readonly int RequeueAfterSeconds;
        public readonly Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMatrixGeneratorsPluginTemplate Template;
        public readonly ImmutableDictionary<string, string> Values;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorsMatrixGeneratorsPlugin(
            Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMatrixGeneratorsPluginConfigMapRef configMapRef,

            Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMatrixGeneratorsPluginInput input,

            int requeueAfterSeconds,

            Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsMatrixGeneratorsPluginTemplate template,

            ImmutableDictionary<string, string> values)
        {
            ConfigMapRef = configMapRef;
            Input = input;
            RequeueAfterSeconds = requeueAfterSeconds;
            Template = template;
            Values = values;
        }
    }
}
