// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1
{

    /// <summary>
    /// Health contains information about the application's current health status
    /// </summary>
    [OutputType]
    public sealed class ApplicationStatusHealth
    {
        /// <summary>
        /// Message is a human-readable informational message describing the health status
        /// </summary>
        public readonly string Message;
        /// <summary>
        /// Status holds the status code of the application or resource
        /// </summary>
        public readonly string Status;

        [OutputConstructor]
        private ApplicationStatusHealth(
            string message,

            string status)
        {
            Message = message;
            Status = status;
        }
    }
}
