// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1
{

    [OutputType]
    public sealed class ApplicationStatusOperationStateOperationSyncSourceKustomizeReplicas
    {
        /// <summary>
        /// Number of replicas
        /// </summary>
        public readonly Union<int, string> Count;
        /// <summary>
        /// Name of Deployment or StatefulSet
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private ApplicationStatusOperationStateOperationSyncSourceKustomizeReplicas(
            Union<int, string> count,

            string name)
        {
            Count = count;
            Name = name;
        }
    }
}
