// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorsScmProviderBitbucketServer
    {
        public readonly bool AllBranches;
        public readonly string Api;
        public readonly Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsScmProviderBitbucketServerBasicAuth BasicAuth;
        public readonly string Project;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorsScmProviderBitbucketServer(
            bool allBranches,

            string api,

            Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsScmProviderBitbucketServerBasicAuth basicAuth,

            string project)
        {
            AllBranches = allBranches;
            Api = api;
            BasicAuth = basicAuth;
            Project = project;
        }
    }
}
