// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1
{

    /// <summary>
    /// GroupKind specifies a Group and a Kind, but does not force a version.  This is useful for identifying concepts during lookup stages without having partially valid types
    /// </summary>
    [OutputType]
    public sealed class AppProjectSpecClusterResourceWhitelist
    {
        public readonly string Group;
        public readonly string Kind;

        [OutputConstructor]
        private AppProjectSpecClusterResourceWhitelist(
            string group,

            string kind)
        {
            Group = group;
            Kind = kind;
        }
    }
}
