// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1
{

    /// <summary>
    /// AppProjectStatus contains status information for AppProject CRs
    /// </summary>
    [OutputType]
    public sealed class AppProjectStatus
    {
        /// <summary>
        /// JWTTokensByRole contains a list of JWT tokens issued for a given role
        /// </summary>
        public readonly ImmutableDictionary<string, Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.AppProjectStatusJwtTokensByRole> JwtTokensByRole;

        [OutputConstructor]
        private AppProjectStatus(ImmutableDictionary<string, Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.AppProjectStatusJwtTokensByRole> jwtTokensByRole)
        {
            JwtTokensByRole = jwtTokensByRole;
        }
    }
}
