// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1
{

    /// <summary>
    /// AppProjectSpec is the specification of an AppProject
    /// </summary>
    [OutputType]
    public sealed class AppProjectSpec
    {
        /// <summary>
        /// ClusterResourceBlacklist contains list of blacklisted cluster level resources
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.AppProjectSpecClusterResourceBlacklist> ClusterResourceBlacklist;
        /// <summary>
        /// ClusterResourceWhitelist contains list of whitelisted cluster level resources
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.AppProjectSpecClusterResourceWhitelist> ClusterResourceWhitelist;
        /// <summary>
        /// Description contains optional project description
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// Destinations contains list of destinations available for deployment
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.AppProjectSpecDestinations> Destinations;
        /// <summary>
        /// NamespaceResourceBlacklist contains list of blacklisted namespace level resources
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.AppProjectSpecNamespaceResourceBlacklist> NamespaceResourceBlacklist;
        /// <summary>
        /// NamespaceResourceWhitelist contains list of whitelisted namespace level resources
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.AppProjectSpecNamespaceResourceWhitelist> NamespaceResourceWhitelist;
        /// <summary>
        /// OrphanedResources specifies if controller should monitor orphaned resources of apps in this project
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.AppProjectSpecOrphanedResources OrphanedResources;
        /// <summary>
        /// PermitOnlyProjectScopedClusters determines whether destinations can only reference clusters which are project-scoped
        /// </summary>
        public readonly bool PermitOnlyProjectScopedClusters;
        /// <summary>
        /// Roles are user defined RBAC roles associated with this project
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.AppProjectSpecRoles> Roles;
        /// <summary>
        /// SignatureKeys contains a list of PGP key IDs that commits in Git must be signed with in order to be allowed for sync
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.AppProjectSpecSignatureKeys> SignatureKeys;
        /// <summary>
        /// SourceNamespaces defines the namespaces application resources are allowed to be created in
        /// </summary>
        public readonly ImmutableArray<string> SourceNamespaces;
        /// <summary>
        /// SourceRepos contains list of repository URLs which can be used for deployment
        /// </summary>
        public readonly ImmutableArray<string> SourceRepos;
        /// <summary>
        /// SyncWindows controls when syncs can be run for apps in this project
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.AppProjectSpecSyncWindows> SyncWindows;

        [OutputConstructor]
        private AppProjectSpec(
            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.AppProjectSpecClusterResourceBlacklist> clusterResourceBlacklist,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.AppProjectSpecClusterResourceWhitelist> clusterResourceWhitelist,

            string description,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.AppProjectSpecDestinations> destinations,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.AppProjectSpecNamespaceResourceBlacklist> namespaceResourceBlacklist,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.AppProjectSpecNamespaceResourceWhitelist> namespaceResourceWhitelist,

            Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.AppProjectSpecOrphanedResources orphanedResources,

            bool permitOnlyProjectScopedClusters,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.AppProjectSpecRoles> roles,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.AppProjectSpecSignatureKeys> signatureKeys,

            ImmutableArray<string> sourceNamespaces,

            ImmutableArray<string> sourceRepos,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Argoproj.V1Alpha1.AppProjectSpecSyncWindows> syncWindows)
        {
            ClusterResourceBlacklist = clusterResourceBlacklist;
            ClusterResourceWhitelist = clusterResourceWhitelist;
            Description = description;
            Destinations = destinations;
            NamespaceResourceBlacklist = namespaceResourceBlacklist;
            NamespaceResourceWhitelist = namespaceResourceWhitelist;
            OrphanedResources = orphanedResources;
            PermitOnlyProjectScopedClusters = permitOnlyProjectScopedClusters;
            Roles = roles;
            SignatureKeys = signatureKeys;
            SourceNamespaces = sourceNamespaces;
            SourceRepos = sourceRepos;
            SyncWindows = syncWindows;
        }
    }
}
