// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1
{

    public class ApplicationSetSpecGeneratorsScmProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("azureDevOps")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsScmProviderAzureDevOpsArgs>? AzureDevOps { get; set; }

        [Input("bitbucket")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsScmProviderBitbucketArgs>? Bitbucket { get; set; }

        [Input("bitbucketServer")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsScmProviderBitbucketServerArgs>? BitbucketServer { get; set; }

        [Input("cloneProtocol")]
        public Input<string>? CloneProtocol { get; set; }

        [Input("filters")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsScmProviderFiltersArgs>? _filters;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsScmProviderFiltersArgs> Filters
        {
            get => _filters ?? (_filters = new InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsScmProviderFiltersArgs>());
            set => _filters = value;
        }

        [Input("gitea")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsScmProviderGiteaArgs>? Gitea { get; set; }

        [Input("github")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsScmProviderGithubArgs>? Github { get; set; }

        [Input("gitlab")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsScmProviderGitlabArgs>? Gitlab { get; set; }

        [Input("requeueAfterSeconds")]
        public Input<int>? RequeueAfterSeconds { get; set; }

        [Input("template")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsScmProviderTemplateArgs>? Template { get; set; }

        public ApplicationSetSpecGeneratorsScmProviderArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorsScmProviderArgs Empty => new ApplicationSetSpecGeneratorsScmProviderArgs();
    }
}
