// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1
{

    /// <summary>
    /// Directory holds path/directory specific options
    /// </summary>
    public class ApplicationOperationSyncSourcesDirectoryArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Exclude contains a glob pattern to match paths against that should be explicitly excluded from being used during manifest generation
        /// </summary>
        [Input("exclude")]
        public Input<string>? Exclude { get; set; }

        /// <summary>
        /// Include contains a glob pattern to match paths against that should be explicitly included during manifest generation
        /// </summary>
        [Input("include")]
        public Input<string>? Include { get; set; }

        /// <summary>
        /// Jsonnet holds options specific to Jsonnet
        /// </summary>
        [Input("jsonnet")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationOperationSyncSourcesDirectoryJsonnetArgs>? Jsonnet { get; set; }

        /// <summary>
        /// Recurse specifies whether to scan a directory recursively for manifests
        /// </summary>
        [Input("recurse")]
        public Input<bool>? Recurse { get; set; }

        public ApplicationOperationSyncSourcesDirectoryArgs()
        {
        }
        public static new ApplicationOperationSyncSourcesDirectoryArgs Empty => new ApplicationOperationSyncSourcesDirectoryArgs();
    }
}
