// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1
{

    public class ApplicationSetSpecArgs : global::Pulumi.ResourceArgs
    {
        [Input("generators", required: true)]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsArgs>? _generators;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsArgs> Generators
        {
            get => _generators ?? (_generators = new InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetSpecGeneratorsArgs>());
            set => _generators = value;
        }

        [Input("goTemplate")]
        public Input<bool>? GoTemplate { get; set; }

        [Input("preservedFields")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetSpecPreservedFieldsArgs>? PreservedFields { get; set; }

        [Input("strategy")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetSpecStrategyArgs>? Strategy { get; set; }

        [Input("syncPolicy")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetSpecSyncPolicyArgs>? SyncPolicy { get; set; }

        [Input("template", required: true)]
        public Input<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetSpecTemplateArgs> Template { get; set; } = null!;

        public ApplicationSetSpecArgs()
        {
        }
        public static new ApplicationSetSpecArgs Empty => new ApplicationSetSpecArgs();
    }
}
