// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1
{

    /// <summary>
    /// Retry controls the strategy to apply if a sync fails
    /// </summary>
    public class ApplicationOperationRetryArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Backoff controls how to backoff on subsequent retries of failed syncs
        /// </summary>
        [Input("backoff")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationOperationRetryBackoffArgs>? Backoff { get; set; }

        /// <summary>
        /// Limit is the maximum number of attempts for retrying a failed sync. If set to 0, no retries will be performed.
        /// </summary>
        [Input("limit")]
        public Input<int>? Limit { get; set; }

        public ApplicationOperationRetryArgs()
        {
        }
        public static new ApplicationOperationRetryArgs Empty => new ApplicationOperationRetryArgs();
    }
}
