// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1
{

    public class ApplicationSetStatusApplicationStatusArgs : global::Pulumi.ResourceArgs
    {
        [Input("application", required: true)]
        public Input<string> Application { get; set; } = null!;

        [Input("lastTransitionTime")]
        public Input<string>? LastTransitionTime { get; set; }

        [Input("message", required: true)]
        public Input<string> Message { get; set; } = null!;

        [Input("status", required: true)]
        public Input<string> Status { get; set; } = null!;

        [Input("step", required: true)]
        public Input<string> Step { get; set; } = null!;

        public ApplicationSetStatusApplicationStatusArgs()
        {
        }
        public static new ApplicationSetStatusApplicationStatusArgs Empty => new ApplicationSetStatusApplicationStatusArgs();
    }
}
