// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1
{

    public class ApplicationSetStatusArgs : global::Pulumi.ResourceArgs
    {
        [Input("applicationStatus")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetStatusApplicationStatusArgs>? _applicationStatus;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetStatusApplicationStatusArgs> ApplicationStatus
        {
            get => _applicationStatus ?? (_applicationStatus = new InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetStatusApplicationStatusArgs>());
            set => _applicationStatus = value;
        }

        [Input("conditions")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetStatusConditionsArgs>? _conditions;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetStatusConditionsArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1.ApplicationSetStatusConditionsArgs>());
            set => _conditions = value;
        }

        public ApplicationSetStatusArgs()
        {
        }
        public static new ApplicationSetStatusArgs Empty => new ApplicationSetStatusArgs();
    }
}
