// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Argoproj.V1Alpha1
{

    /// <summary>
    /// JWTToken holds the issuedAt and expiresAt values of a token
    /// </summary>
    public class AppProjectSpecRolesJwtTokensArgs : global::Pulumi.ResourceArgs
    {
        [Input("exp")]
        public Input<int>? Exp { get; set; }

        [Input("iat", required: true)]
        public Input<int> Iat { get; set; } = null!;

        [Input("id")]
        public Input<string>? Id { get; set; }

        public AppProjectSpecRolesJwtTokensArgs()
        {
        }
        public static new AppProjectSpecRolesJwtTokensArgs Empty => new AppProjectSpecRolesJwtTokensArgs();
    }
}
